### ISSUE TITLE
privacy concerns

### ISSUE THREAD

**Issue by sedrubal** [fourcube/goiban-service#4]
- You write:

```
Private
No data is stored. No request logs are written. Everything works in memory.
```

But in the same way you provide statistics... I think this can't work...

 - And you write:

```
Secure
You can use the HTTPS version of this service.
```

Don't you want to automatically redirect HTTP to HTTPS?

**Comment by fourcube** [comment]
Thanks for raising your concerns. 

The statistics simply count the country prefixes of each validation request. It's just meant as a demo for users who want to host `goiban-service` themselves. (this is the code https://github.com/fourcube/goiban-service/blob/master/metrics/metrics.go#L42-L46)

I have considered to automatically redirect HTTP requests to HTTPS, but I did not want to break compatibility for users who rely on the HTTP version of the service. I would actually love to do this, but there are two things that stop me from immediately doing the change:

1. I don't know who still uses the HTTP part of the service because of the no-logging policy.
2. I have no way to contact users of the service and inform them that a switch to HTTPS is happening. 

It would not be too hard for me to monitor the HTTP usage without logging anything, so I will try to do that some time soon. The switch would have to be very long term (may 1/2y), in the hope that the users/developers actually visit the site infrequently.

**Comment by sedrubal** [comment]
Ah ok.

 - The point, I wanted to complain about, is: I think it might not be 100% correct, when you write that you don't store any data... I think, when you write, you don't store any *personal* data, it would be better... ;)
 - Ah I understand your concerns about HTTPS... But as it isn't recommended for all to expose those personal data to a HTTP connection, I would force the people to use HTTPS ;) and normally I think switching to HTTPS is not a big problem. You could maybe add a notification to the website so that everybody sees the cause when his service breaks.

**Comment by fourcube** [comment]
@sedrubal the switch to SSL-only is coming on March 27th.

**Comment by fourcube** [comment]
Closing this issue after the switch to SSL-only mode. Thanks again!
